### ISSUE TITLE
Bug migration

### ISSUE THREAD

**Issue by ailin-nemui** [irssi/irssi#26]
https://github.com/ahf/irssi-old/issues
https://github.com/ahf/irssi-old/issues/8
https://github.com/irssi-import/bugs.irssi.org/issues
http://bugs.debian.org/irssi
http://bugz.fedoraproject.org/irssi

(copied from https://github.com/ahf/irssi-old/issues/8 - added github flavored markdown checkboxes to use as task list)

haspatch:
- [x] [FS#798](https://github.com/irssi-import/bugs.irssi.org/issues/798) - patch Irssi::signal_remove to allow removal of handlers created with coderef callbacks 
- [x] [FS#902](https://github.com/irssi-import/bugs.irssi.org/issues/902) - Empty lines in output of "exec" command cause "Not enough parameters given" errors 
- [ ] [FS#383](https://github.com/irssi-import/bugs.irssi.org/issues/383) - http proxy + ssl crypts CONNECT 
- [x] [FS#60](https://github.com/irssi-import/bugs.irssi.org/issues/60) - 2 icb bugs
- [x] [FS#621](https://github.com/irssi-import/bugs.irssi.org/issues/621) - [PATCH] Color support for "gui_entry" to allow better spellcheckers.
- [x] [FS#733](https://github.com/irssi-import/bugs.irssi.org/issues/733) - Please don't translate capital letter in channel name into small letter
- [x] [FS#749](https://github.com/irssi-import/bugs.irssi.org/issues/749) - [patch] make xirssi work with latest SVN
- [x] [FS#781](https://github.com/irssi-import/bugs.irssi.org/issues/781) - write_buffer causes awaylog to miss messages (patch included)
- [ ] [FS#827](https://github.com/irssi-import/bugs.irssi.org/issues/827) - missed redraws due to concurrency error
- [ ] [FS#893](https://github.com/irssi-import/bugs.irssi.org/issues/893) - problem that recode doesn't affect nicknames and topic, ownnick..
- [x] [FS#275](https://github.com/irssi-import/bugs.irssi.org/issues/275) - /hilight -mask -line nick!_@_ fails
- [x] [FS#531](https://github.com/irssi-import/bugs.irssi.org/issues/531) - [PATCH] Add signal for paste detection events
- [ ] [FS#725](https://github.com/irssi-import/bugs.irssi.org/issues/725) - window move up/down loses windows
- [x] [FS#904](https://github.com/irssi-import/bugs.irssi.org/issues/904) - paste_buffer_join_lines() - wrong use of "paste_buffer" variable 
- [x] http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=637175 perl dcc file size issue

(confirmed still an issue)
- [ ] [FS#5](https://github.com/irssi-import/bugs.irssi.org/issues/5) /action #channel doesn't use action_public_channel format 
- [x] [FS#124](https://github.com/irssi-import/bugs.irssi.org/issues/124) ", x<left><tab>" in a query triggers assertion failures
- [x] [FS#127](https://github.com/irssi-import/bugs.irssi.org/issues/127) probably many issues with paste_detection
- [x] [FS#377](https://github.com/irssi-import/bugs.irssi.org/issues/377) - away messages failed to show 

shouldcheck:
- [x] [FS#156](https://github.com/irssi-import/bugs.irssi.org/issues/156) spaces in dcc filenames (happens in xchat 2.4.4, not in the latest version, can be ignored)
- [x] [FS#331](https://github.com/irssi-import/bugs.irssi.org/issues/331) !channels and layout save (#183)
- [x] [FS#782](https://github.com/irssi-import/bugs.irssi.org/issues/782) [FS#816](https://github.com/irssi-import/bugs.irssi.org/issues/816) - Wrong string length calculation for sbar
- [ ] [FS#786](https://github.com/irssi-import/bugs.irssi.org/issues/786) - $[num]variable syntax truncates to zero width and worse in nested templates
- [ ] [FS#107](https://github.com/irssi-import/bugs.irssi.org/issues/107) - /me action and hilight
- [ ] [FS#158](https://github.com/irssi-import/bugs.irssi.org/issues/158) - Padding and length calculation of arguments ($...) is broken
- [ ] [FS#464](https://github.com/irssi-import/bugs.irssi.org/issues/464) - server connection msgs go to 2 windows rather than just 1 or many more
- [ ] [FS#473](https://github.com/irssi-import/bugs.irssi.org/issues/473) - alternate_nick to null at connect
- [ ] [FS#703](https://github.com/irssi-import/bugs.irssi.org/issues/703) - HIlight inside action doesn't end up in awaylog
- [ ] [FS#720](https://github.com/irssi-import/bugs.irssi.org/issues/720) - "/ignore -except #channel QUITS" not working as expected
- [x] [FS#579](https://github.com/irssi-import/bugs.irssi.org/issues/579) - Irssi does not fall back to to IPv4 address if IPv6 address is unreacable

github forks:
- [ ] https://github.com/shabble/irssi/branches
- [ ] https://github.com/ensc/irssi-proxy/tree/master
- [ ] https://github.com/msparks/irssi-old/compare/master...ms
- [ ] https://github.com/zewt/irssi/commits/master
- [ ] https://github.com/ThomasHabets/irssi/commits/master
- [ ] https://github.com/m1el/irssi/commit/6f8f2b45f7de1befbfa157a3a5b3d6c01bac3946?w=1
- [x] https://github.com/lyska/irssi/commits/master
- [ ] https://github.com/xinutec/irssi/commits/master
- [x] https://github.com/Aerdan/irssi/commits?author=Aerdan
- [x] https://github.com/gparent/irssi/commits/master?author=gparent
- [ ] https://github.com/mauke/irssi-hax/commits/master
- [ ] https://github.com/evalfile/irssi/commits/master?author=evalfile

(thanks @dequis)

**Comment by dequis** [comment]
[FS#733][] was fixed with 518b822db451a863b9496e985b10b88c50339582 (included in 0.8.16)

[FS#331][] is now #183 ("/layout save stores the "visible name" of !-channels (safe channels) instead of the real one")

[FS#275][] ("/hilight -mask -line nick!*@* fails") is "similar" to #249 ("Highlighting with -word matches both nick and message instead of only message")

[FS#275]: http://bugs.irssi.org/index.php?do=details&task_id=275
[FS#331]: http://bugs.irssi.org/index.php?do=details&task_id=331
[FS#733]: http://bugs.irssi.org/index.php?do=details&task_id=733

The Aerdan fork had a single commit, equivalent to 0e294d5c2e4d4dd686378f2050abc9a9f2fae199 (included in 0.8.17)

The lyska fork no longer exists, owner says "basically I found some irssi patches and applied them, but then it got unstable and I lost interest. it was the 256 color patch, etc"

The gparent fork is now a fork of this repo, but has a ssl-fingerprint branch.

**Comment by GeertHauwaerts** [comment]
The following actions have been performed on the old bug tracker:

* [FS#733](http://bugs.irssi.org/index.php?do=details&task_id=733) has been closed as fixed
* [FS#331](http://bugs.irssi.org/index.php?do=details&task_id=331) has been closed as deferred to GitHub

**Comment by verkel** [comment]
I'd like this old bug fixed: http://bugs.irssi.org/index.php?do=details&task_id=833

It has a patch as well, although the poster is unsure if his fix is polished enough or even correct. Still could be worth checking out?

For my use-case, I'd like this functionality for use with the Bitlbee IM gateway in combination with Irssi. When I use an alternate client for sending IM messages, let's say Facebook web chat, messages from my own nick end up in a query window with my nick, rather than to the query named after the person I'm talking with. I'd rather have the whole conversation in the single query window, as if I would be talking through Irssi.

**Comment by dequis** [comment]
@verkel I was going to say that you should open a new ticket instead of commenting here, but that bug in particular is already fixed in 0.8.18-beta. This is also mentioned in the [bitlbee docs][1]

[1]: https://wiki.bitlbee.org/SelfMessages

**Comment by verkel** [comment]
@dequis Thanks for the info! I saw ZNC bouncer's page of clients which support local echo, from where the list was originally copied into Bitlbee's wiki. I hadn't seen the Bitlbee's wiki page though, until you linked it.

**Comment by madduck** [comment]
@ailin-nemui how does this work? I can definitely confirm that

> FS#579 - Irssi does not fall back to to IPv4 address if IPv6 address is unreacable

listed under "shouldcheck" is a bug, and it hurts. Would it help if I filed a new Github issue? I will also look at the code, sure, but where do I keep track of information I find?

**Comment by ailin-nemui** [comment]
@madduck I believe https://github.com/irssi/irssi/issues/190 is related discussion at least, but this may also be a separate issue for which you should open a new issue. I suspect it may be good to investigate this issue also with some output like the one shown in irssi's status window and from `getent ahosts servername`.

**Comment by madduck** [comment]
@ailin-nemui I am not sure #190 is actually related, other than them both dealing with IPv6-IPv4 interplay. Then again, properly solving this once and for all is probably going to address both issues. But I'll file a separate one for FS#579 for now…
